### ISSUE TITLE
Improve the post deploy flow

### ISSUE THREAD

**Issue by talkol** [ton-defi-org/jetton-deployer-webclient#9]
Let's be a little more user friendly after a user finished deploying like:

1. Give a very clear main screen indication of the contract address

2. Give a link in a TON block explorer to see the contract

3. Provide instructions how to see your jetton in a supported wallet so people can send it around

**Comment by shaharyakir** [comment]
@denis-orbs only 3 remains (would redirect to [sandbox/testnet/].scaleton.io

**Comment by shaharyakir** [comment]
3 is redundant now due to #45
